const btnsBreak = document.querySelectorAll('.container.break button');
const btnsSession = document.querySelectorAll('.container.session button');
const sessionLengthDisplay = document.getElementById('session-length');
const breakLengthDisplay = document.getElementById('break-length');
const timeLeft = document.getElementById('time-left');
const btnStartStop = document.getElementById('start_stop');
const btnReset = document.getElementById('reset');
const timerLabel = document.getElementById('timer-label');
const audio = document.getElementById('beep');